### ISSUE TITLE
局部化定制 panel 样式

### ISSUE THREAD

**Issue by jzoe** [zuiidea/antd-admin#415]
如果我只想定义一个 panel 的 header 的背景颜色，应该如何实现？

在 `themes/index.less` 中修改的话，会使得全局的 panel 颜色都被修改了。

我试着在相应的 components 的 less 文件中设置，但无法生效：
```css
.buleHeader {
  :global .ant-collapse {
    .ant-collapse-item {
      .ant-collapse-header {
        color: #ffffff; //标题字体颜色
        background-color: #108ee9; //标题背景色
      }
    }
  }
}
```
在我的 js 文件中用如下的方式应用:
```javascript
import styles from './XXX.less'
...
<Collapse defaultActiveKey={['1']} className={styles.buleHeader }>
  <Panel header="蓝色标题panel" key="1">
 </Panel>
...
</Collapse>
```
在 `Panel` 中直接指定 style 的话，能修改背景色，但字体颜色没有修改成功
```javascript
import styles from './XXX.less'
...
<Collapse defaultActiveKey={['1']} >
  <Panel header="蓝色标题panel" key="1" style={{ "background-color": '#108ee9'， color: '#fff' }}>
 </Panel>
...
</Collapse>
```
